# Made with love by Puyodead1
# 
# Change LicenseKey to the license key provided
# The Debug switch sends debug messages to all players (some)
# ParticlesEnabled controls particles on IT
# StatsEnabled: If set to false, stats system will be turned off
# HologramEnabled: If set to false, holograms will not be shown to players when they join, 
# if you set this to true, you MUST set the hologram location!
# 
# DO NOT CHANGE ExitLocationSet, ArenaCoordinate1Set, ArenaCoordinate2Set, or HologramLocationSet!
# 
# The StatsHologram area is for customization of the hologram, you can add as many lines as you want with color support! 
# Valid placeholders for the hologram are: {PLAYER_NAME}, {KBTSTAT_1}, {KBTSTAT_2}, {KBTSTAT_3}, {KBTSTAT_4}
# Make sure you use this format:
# StatsHologram:
#  - "&6Line 1"
#  - "&7Line 2"
#
LicenseKey: ""
Debug: false
ParticlesEnabled: false
StatsEnabled: true
HologramEnabled: false
ExitLocationSet: false
ArenaCoordinate1Set: false
ArenaCoordinate2Set: false
HologramLocationSet: false

StatsHologram:
  - "&7*** &6&lStats &7***"
  - "&ePlayer: &7{PLAYER_NAME}"
  - "&eStat1: &7{KBTSTAT_1}"
  - "&eStat2: &7{KBTSTAT_2}"
  - "&eStat3: &7{KBTSTAT_3}"
  - "&eStat4: &7{KBTSTAT_4}"