name: KnockBackTag
main: me.puyodead1.KBT.KnockBackTag
version: 1.0 Beta 2 Alpha 1
author: Puyodead1
description: Custom Tag Minigame
commands:
  mg-kbt:
    description: OP Base Command
  EnterGame: 
    description: Enter the Arena
  Leave:
    description: Leave the Arena
  ExitCoordinate:
    description: Set the Exit Location